#!/bin/bash
# 20-configure-apt
#
# This script configure apt
#

#
# Setup the sources.list file for new installations of Canaima GNU/Linux.
#

# disable apt sources.list base
sed -i 's/^deb/#deb/' $ROOTFS/etc/apt/sources.list

cat <<E_O_APT > $ROOTFS/etc/apt/sources.list.d/canaima.list
# oficial
deb $MIRROR $SUITE main aportes
E_O_APT

cat <<EOF > $ROOTFS/etc/apt/apt.conf.d/10-$DIST
Acquire::PDiffs "false";
// Acquire::Language "none";
APT::Clean-Installed "true";
APT::Get:AutomaticRemove "true";
APT::Get::HideAutoRemove "false";
APT::Get:Show-Upgraded "true";
APT::Install-Recommends "false";
EOF

cat <<EOF > $ROOTFS/etc/apt/apt.conf.d/80-update
Acquire::Check-Valid-Until "false";
EOF

cat <<EOF > $ROOTFS/etc/apt/preferences.d/$DIST.pref
Package: *
Pin: release n=$SUITE
Pin-Priority: 999

EOF

cat <<EOF > $ROOTFS/etc/apt/apt.conf.d/90-recommends
APT::Install-Recommends "false";
EOF

#
#  Now that the sources have been setup make sure the system is up to date.
#
chroot $ROOTFS /usr/bin/apt-get update
chroot $ROOTFS /usr/bin/apt-get upgrade -y

#
# install basic packages from Canaima
#
install_package canaima-base canaima-llaves lsb-base base-files
