#!/bin/bash
# 30-configure-locales
#
# install and configure locales
#

#
#  Install locales
#
install_package locales
install_package util-linux-locales

#
# define locales
#
chroot $ROOTFS /usr/sbin/update-locale LANG=C

#
# Default to the same locale as the host.
#
if [ -e /etc/locale.gen ]; then
   cp /etc/locale.gen $ROOTFS/etc
fi
chroot $ROOTFS /usr/sbin/locale-gen

