#!/bin/bash
# 02-configure-sysctl
#
# configure sysctl
#

cat <<SYSCTL_EOF >>$ROOTFS/etc/sysctl.conf
# VM
vm.dirty_ratio = 20
vm.dirty_background_ratio = 20
vm.dirty_bytes = 67108864
vm.dirty_background_bytes = 134217728
# swapping
vm.swappiness = 0
vm.vfs_cache_pressure = 40
# fs
fs.aio-max-nr = 1048576
fs.file-max = 287573
#cantidad de hilos maximos
kernel.threads-max = 98006
# disable ipv6
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
# ipv4 settings
net.ipv4.tcp_rmem = 4096 87380 16777216
net.ipv4.tcp_wmem = 4096 65536 16777216
net.ipv4.tcp_mem = 8388608 8388608 8388608
net.ipv4.tcp_congestion_control = htcp
net.ipv4.tcp_rfc1337 = 1
net.ipv4.tcp_sack = 1
net.ipv4.tcp_fack = 1
net.ipv4.tcp_window_scaling = 1
net.ipv4.tcp_max_tw_buckets = 500000
# number of packets to keep in backlog before the kernel starts dropping them
net.ipv4.tcp_max_syn_backlog = 3240000
# increase socket listen backlog
net.core.somaxconn = 3240000
net.ipv4.tcp_max_tw_buckets = 1440000
# memory
kernel.sem = 100 32000 100 128
SYSCTL_EOF
