#!/bin/bash
# 10-enable-epel
#
# add epel repository
#

# TODO automate get name


for trynumber in 1 2 3; do
    [ $trynumber != 1 ] && echo "Trying again..."
	chroot $ROOTFS /bin/rpm -iUvh "http://download.fedoraproject.org/pub/epel/6/i386/epel-release-6-8.noarch.rpm"
	if [ $? -ne 0 ]; then
		echo "Failed to get a epel-release"
        continue
    fi
    break
done

chroot $ROOTFS /usr/bin/yum -y update

# === basic packages
chroot $ROOTFS /usr/bin/yum -y --enablerepo=epel lsof rsync screen htop bind-utils sysstat wget nc
