#!/bin/bash
# 25-disable-selinux
#
# Disable selinux in the container
#

mkdir -p $ROOTFS/selinux
echo 0 > $ROOTFS/selinux/enforce

# disable selinux
sed -i.orig -e "s/enforcing/disabled/" /etc/sysconfig/selinux
