#!/bin/bash
# 99-disable-udev
#
# disable udev and sysinit
#

# disable udev
sed -i 's/\/sbin\/start_udev/#\/sbin\/start_udev/' $ROOTFS/etc/rc.sysinit
sed -i 's/\/sbin\/start_udev/#\/sbin\/start_udev/' $ROOTFS/etc/rc.d/rc.sysinit

cat <<EOF >> $ROOTFS/etc/rc.d/rc.sysinit
exit 0
EOF

# don't mount devpts, for pete's sake
sed -i '/^mount -n \/dev\/pts.*$/s|^|#|' $ROOTFS/etc/rc.sysinit
sed -i '/^mount -n \/dev\/pts.*$/s|^|#|' $ROOTFS/etc/rc.d/rc.sysinit
