#!/bin/bash
# ================================================================================
# LXC-tools: Appliance and LXC container builder for Debian GNU/Linux (and derivatives)
#
# Copyright © 2010 Jesús Lara Giménez (phenobarbital) <jesuslara@devel.com.ve>>
# Version: 0.4
#
#    Developed by Jesus Lara (phenobarbital) <jesuslara@phenobarbital.info>
#    https://github.com/phenobarbital/lxc-tools
#    
#    This script is based on the lxc-debian example script that ships with lxc.
#    Copyright (C) 2010 Nigel McNie
#
#    License: GNU GPL version 3  <http://gnu.org/licenses/gpl.html>.
#    This is free software: you are free to change and redistribute it.
#    There is NO WARRANTY, to the extent permitted by law.
# ================================================================================

###
# lxct_info
# get information about environment, lxc and lxc-tools
##

if [ "$(id -u)" != "0" ]; then
   echo "$(basename $0): must be run as root" >&2
   exit 1
fi

# get configuration
if [ -e /etc/lxc-tools/lxc-tools.conf ]; then
    . /etc/lxc-tools/lxc-tools.conf
else
    . ./etc/lxc-tools.conf
fi

#
#  fill all "auto" variables and check configuration
#
if [ -e /usr/lib/lxc-tools/config.sh ]; then
    . /usr/lib/lxc-tools/config.sh
else
    . ./lib/config.sh
fi

# get general info about LXC
# TODO: using colored info
cat << _MSG

 ****************** [ LXC-tools General Information ] *******************
 *
 * LXC version : ................... $LXC
 * Distribution : .................. $DIST
 * Suite : ......................... $SUITE
 * Arch : .......................... $ARCH
 * Bridge : ........................ $BRIDGE
 * Gateway : ....................... $GATEWAY
 * Netmask : ....................... $NETMASK
 * Network : ....................... $NETWORK
 * Install Mode : .................. $BACKEND_METHOD
 * Network Mode : .................. $NET_TYPE
 *
 ************************************************************************
 
 ********************* [ LXC check configuration ] ********************** 
 
 $(lxc-checkconfig)
 
 ************************************************************************ 
_MSG
