#!/bin/bash
#
# Create a minimal version of container
#

set -e

prefix=$1

#
#  Install some new packages - do this first to avoid dependency errors.
#
install_package syslog-ng 
install_package deborphan
install_package less
install_package screen
install_package sudo
install_package vim

#
#  Remove some standard packages.
#

# PPP stuff.
remove_package pppconfig
remove_package pppoeconf
remove_package pppoe
remove_package ppp
remove_package libpcap0.7

# Editors
remove_package nano
remove_package ed
remove_package nvi

# Syslog
remove_package klogd
remove_package sysklogd

# manpages
remove_package manpages  
remove_package man-db 
remove_package info

# misc
remove_package tasksel tasksel-data
remove_package pciutils
remove_package fdutils
remove_package cpio
