#!/bin/bash
#
# Stub file: (test role)
#

set -e

# return container's rootfs
prefix=$1

#
# Log our start
#
message "role stub starting"

info "\n Running role in ${prefix} \n"

#
# install an example package
#
install_package git-core
# configure git
chroot ${prefix} /usr/bin/git config --global user.name "$NAME"
chroot ${prefix} /usr/bin/git config --global user.email "root@$HOSTNAME"

#
#  Log our finish
#
message "role stub finished"
