#!/bin/bash
#
# Stub file: (test role)
#

set -e

# return container's rootfs
prefix=$1

#
# Log our start
#
message "role stub starting"

info "Running role in ${prefix}"

#
#  Log our finish
#
message "role stub finished"
