#!/bin/bash
# 50-configure-services
#
# configure centos services
#

# enable SSH
chroot $ROOTFS systemctl enable sshd.service

# blacklist ipv6
cat <<EOF >> $ROOTFS/etc/modprobe.d/blacklist
blacklist ipv6
blacklist net-pf-10
EOF
