#!/bin/bash
# 50-configure-services
#
# configure centos services
#

# install SSH
chroot $ROOTFS /usr/bin/yum -y install openssh-server openssh-clients
# enable SSH
chroot $ROOTFS systemctl enable sshd.service

# enable network
chroot $ROOTFS chkconfig network on

# blacklist ipv6
cat <<EOF >> $ROOTFS/etc/modprobe.d/blacklist
blacklist ipv6
blacklist net-pf-10
EOF
