#!/bin/bash
# 01-disable-daemons
#
#  This script ensures that daemons will not be started inside our
# chroot() installation.
#
if [ ! -d "$ROOTFS/usr/sbin" ]; then

    mkdir -p "$ROOTFS/usr/sbin"
    message "created missing directory: $ROOTFS/usr/sbin"
fi

#
#  Add the script.
#
echo '#!/bin/sh' >  $ROOTFS/usr/sbin/policy-rc.d
echo 'exit 101'  >> $ROOTFS/usr/sbin/policy-rc.d
chmod 755           $ROOTFS/usr/sbin/policy-rc.d
