#!/bin/bash
# 70-configure-ssh
#
# install and configure SSH
#

#  Create an ssh directory
#
mkdir -p $ROOTFS/etc/ssh

#
# Generate the Host RSA Key
#
if [ ! -f $ROOTFS/etc/ssh/ssh_host_rsa_key ]; then
	if ssh-keygen -t rsa -N "" -f $ROOTFS/etc/ssh/ssh_host_rsa_key -C "root@$NAME"; then
		message "successfully generated Host RSA"
	else
		message "failed to generate Host RSA Key"
	fi
fi

#
# Generate the Host DSA Key
#
if [ ! -f $ROOTFS/etc/ssh/ssh_host_dsa_key ]; then
	if ssh-keygen -t dsa -N "" -f $ROOTFS/etc/ssh/ssh_host_dsa_key -C "root@$NAME"; then
		message "successfully generetaged Host DSA"
	else
		message "failed to generate Host DSA Key"
	fi
fi

#
# Install openssh-server
#
install_package openssh-server

# fix buggus runlevel with sshd
cat <<EOF > $ROOTFS/etc/init/ssh.conf
# ssh - OpenBSD Secure Shell server
#
# The OpenSSH server provides secure shell access to the system.

description	"OpenSSH server"

start on filesystem
stop on runlevel [!2345]

expect fork
respawn
respawn limit 10 5
umask 022
# replaces SSHD_OOM_ADJUST in /etc/default/ssh
oom never

pre-start script
    test -x /usr/sbin/sshd || { stop; exit 0; }
    test -e /etc/ssh/sshd_not_to_be_run && { stop; exit 0; }
    test -c /dev/null || { stop; exit 0; }

    mkdir -p -m0755 /var/run/sshd
end script

# if you used to set SSHD_OPTS in /etc/default/ssh, you can change the
# 'exec' line here instead
exec /usr/sbin/sshd
EOF
