#!/bin/bash
##
#  /usr/lib/lxc-tools/templates.d/lxc-debian
#
#  Build container from debian rules
##
#
# debootstrap debian install
#
# based on:
# Daniel Lezcano <daniel.lezcano@free.fr>
# Authors:
# Jesus Lara <jesuslarag@phenobarbital.info>
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA

download_debian() 
{
	if [ "$ARCH" = 'x86_64' ]; then
		arch='amd64'
	else
		arch='i386'
	fi	
    mkdir -p "$CACHE/$SUITE/partial-$arch"
    if [ $? -ne 0 ]; then
       	error "Failed to create '$CACHE/$SUITE/partial-$arch' directory"
       	return 1
    fi
    # download a mini debian into a cache
    message "Downloading Debian minimal ..."
    debootstrap --verbose --variant=$VARIANT --arch=$arch --include $EXTRA_PACKAGES \
        $SUITE $CACHE/$SUITE/partial-$arch $MIRROR
    RESULT=$?

    if [ "$RESULT" != "0" ]; then
       error "Failed to download the rootfs, aborting."
       rm -fR "$CACHE/$SUITE/partial-$arch"
       return 1
    fi

    mv "$CACHE/$SUITE/partial-$arch" "$CACHE/$SUITE/rootfs-$arch"
    info "Download $DIST $SUITE complete."

    return 0
}

copy_debian()
{
	# make a local copy of the minidebian
	if [ "$ARCH" = 'x86_64' ]; then
		arch='amd64'
	else
		arch='i386'
	fi	
    info "Copying rootfs to $ROOTFS..."
    rsync -aqzpHSW $CACHE/$SUITE/rootfs-$arch/* $ROOTFS/ || return 1
    if [ $? -ne 0 ]; then
		error "Failed to copy rootfs"
        exit 1
    fi
}

install_debian() 
{

    mkdir -p /var/lock/subsys/
    (
        flock -n -x 200
        if [ $? -ne 0 ]; then
            error "Cache repository is busy."
            exit 1
        fi
        
		if [ "$ARCH" = 'x86_64' ]; then
			arch='amd64'
		else
			arch='i386'
		fi	        
		
        # cleaning cache of mini debian
        if [ "$CLEAN_CACHE" -eq "1" ]; then
			message "Cache found in $CACHE/$SUITE/rootfs-$arch. clearing ..."
			rm -fR $CACHE/$SUITE/rootfs-$arch
        fi
        
        # check the mini debian was not already downloaded
        message "Checking cache download in $CACHE/$SUITE/rootfs-$arch ... "
        if [ ! -e "$CACHE/$SUITE/rootfs-$arch" ]; then
            download_debian
            if [ $? -ne 0 ]; then
                error "Failed to download 'Debian Base'"
                exit 1
            fi
        fi
        
        copy_debian
        
        return 0

        ) 200>/var/lock/subsys/lxc-debian

    return $?
}

debian_network()
{
	if [ "$DHCP" = "y" ]; then
cat <<EOF >> $ROOTFS/etc/network/interfaces
# interface $LAN_INTERFACE
auto $LAN_INTERFACE
iface $LAN_INTERFACE inet dhcp
EOF
cat <<EOF >> $ROOTFS/etc/hosts
# $HOSTNAME
127.0.1.1	$HOSTNAME $NAME
EOF
	else
cat <<EOF >> $ROOTFS/etc/network/interfaces
# interface $LAN_INTERFACE
auto $LAN_INTERFACE
iface $LAN_INTERFACE inet static
	address $IP
	netmask $NETMASK
	network $NETWORK
	gateway $GATEWAY
EOF
cat <<EOF >> $ROOTFS/etc/hosts
# $HOSTNAME
$IP	$HOSTNAME $NAME
EOF
	fi
# set the hostname
echo $NAME > $ROOTFS/etc/hostname
echo $HOSTNAME > $ROOTFS/etc/mailname

}

configure_debian()
{
	# configure inittab
	debian_inittab
	# configure via mknod devices
	debian_devices
	# configure debian network
	debian_network
    if [ $? -ne 0 ]; then
		error "Failed to Configure 'Debian Base'"
		return 1
    fi	
	# running basic debian hooks
	DEBIAN="$TEMPLATEDIR/debian.d"
	for f in $(find $DEBIAN/* -maxdepth 1 -type f | sort --numeric-sort); do
		. $f
	done
}

debian_devices()
{
	DEV="$ROOTFS/dev"
	mknod -m 666 ${DEV}/tty c 5 0
    for tty in $(seq 1 2); do
	if [ ! -e $DEV/tty$tty ]; then
	    mknod -m 666 $ROOTFS/dev/tty$tty c 4 $tty
	fi
    done
    rm -f ${DEV}/null
	mknod -m 666 ${DEV}/null c 1 3
	rm -f ${DEV}/zero
    mknod -m 666 ${DEV}/zero c 1 5
    rm -f ${DEV}/random
    mknod -m 666 ${DEV}/random c 1 8
    rm -f ${DEV}/urandom
    mknod -m 666 ${DEV}/urandom c 1 9
    rm -f ${DEV}/console
    mknod -m 600 ${DEV}/console c 5 1
    rm -f ${DEV}/full
    mknod -m 666 ${DEV}/full c 1 7
    # Mount pseudo-filesystems
    mount -o bind /dev/pts "$ROOTFS/dev/pts"
    mount -o bind /proc "$ROOTFS/proc"
    mount -o bind /sys "$ROOTFS/sys"
	# Bind mount systems apt cache
    mount -o bind /var/cache/apt/archives "$ROOTFS/var/cache/apt/archives"
    # configure a minimal fstab for container
cat <<EOF > $ROOTFS/etc/fstab
/dev/root               /                       rootfs   defaults        0 0
devpts                  /dev/pts                devpts  gid=5,mode=620,newinstance,ptmxmode=0666  0 0
none                    /dev/shm                tmpfs    nosuid,nodev    0 0
EOF
   
}

debian_inittab() {
cat <<EOF > $ROOTFS/etc/inittab
id:3:initdefault:
si::sysinit:/etc/init.d/rcS
l0:0:wait:/etc/init.d/rc 0
l1:1:wait:/etc/init.d/rc 1
l2:2:wait:/etc/init.d/rc 2
l3:3:wait:/etc/init.d/rc 3
l4:4:wait:/etc/init.d/rc 4
l5:5:wait:/etc/init.d/rc 5
l6:6:wait:/etc/init.d/rc 6
# Normally not reached, but fallthrough in case of emergency.
z6:6:respawn:/sbin/sulogin
1:2345:respawn:/sbin/getty 38400 console
c1:12345:respawn:/sbin/getty 38400 tty1 linux
c2:12345:respawn:/sbin/getty 38400 tty2 linux
#c3:12345:respawn:/sbin/getty 38400 tty3 linux
#c4:12345:respawn:/sbin/getty 38400 tty4 linux
EOF

}

debian_cleanup()
{
	#
	# clean apt cache
	#
	chroot $ROOTFS /usr/bin/apt-get -y autoremove
	chroot $ROOTFS /usr/bin/apt-get -y clean
	# protect dash and locales
	chroot $ROOTFS /bin/echo locales hold | /usr/bin/dpkg --set-selections
	chroot $ROOTFS /bin/echo dash hold | /usr/bin/dpkg --set-selections
	#  Remove disable-daemons script (if present)
	if [ -x "$ROOTFS/usr/sbin/policy-rc.d" ]; then
		rm -f "$ROOTFS/usr/sbin/policy-rc.d"
	fi
	# Unmount systems apt cache
    umount "$ROOTFS/var/cache/apt/archives"
    rm -f "$ROOTFS/etc/dpkg/dpkg.cfg.d/lxc"
    # Unmount pseudo-filesystems
    umount "$ROOTFS/dev/pts"
    umount "$ROOTFS/proc"
    umount "$ROOTFS/sys"
}


create_container()
{
	info "= Creating a Debian-Based LXC container ="
	# create cache and install Debian
	install_debian
    if [ $? -ne 0 ]; then
		error "Failed to Download and install Debian Base"
		return 1
    fi
	debug "= Configure Debian-Based LXC container ="
	# configure chroot
	configure_debian
    if [ $? -ne 0 ]; then
		error "Failed to Configure Debian Base"
		return 1
    fi		
	info "Debian LXC Container created"
	return 0
}

cleanup_container()
{
	# cleanup debian
	debian_cleanup
	return 0
}
