#!/bin/bash
##
#  /usr/lib/lxc-tools/templates.d/lxc-centosd
#
#  Build container of centos 6.x in Debian 7 using yum+rpm
##
#
# centos 6.x lxc container install
#
# based on:
# Daniel Lezcano <daniel.lezcano@free.fr>
# Ramez Hanna <rhanna@informatiq.org>
#
# Authors:
# Jesus Lara <jesuslarag@phenobarbital.info>
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA

# re-define options
DIST='centos'
SUITE='6'
RELEASE='6-4.el6.centos.10'
RELEASE_FILE=''
MIRROR_URL=''

#TODO: usable inittab

download_centos()
{
	INSTALL_ROOT="$CACHE/$DIST/$SUITE/partial-$ARCH"
	echo $INSTALL_ROOT
	
	WGET="wget --timeout=8 --read-timeout=15 -c -t10 -nd"
	YUM="yum --disablerepo=updates --enablerepo=base --installroot=$INSTALL_ROOT -y --nogpgcheck"
	YUM_CACHE=$INSTALL_ROOT/var/cache/yum/base/packages
    RPM="rpm --root $INSTALL_ROOT --ignorearch"
    
    # create partial directory
	mkdir -p $INSTALL_ROOT
    if [ $? -ne 0 ]; then
		error "Failed to create '$INSTALL_ROOT' directory"
       	return 1
    fi
    
    # create directories for yum
	mkdir -p $INSTALL_ROOT/var/{lib/rpm,cache/yum/base/packages}
	mkdir -p $INSTALL_ROOT/var/cache/yum/$ARCH/$SUITE/base/packages
	
	# and update a yum.conf
	# echo "protected_multilib=1" >> /etc/yum/yum.conf
	
	if [ "$ARCH" = "i686" ]; then
		ARCH='i386'
	fi
	
	#if [ "$ARCH" = "x86_64" ]; then
		# resolve a ¿bug? yum try to install i386 versions of packages
		# echo "exclude=*.i386 *.i686" >> /etc/yum/yum.conf
	#fi
	
    # download centos mirror list
    info "Downloading CentOS mirror list ..."
	MIRRORLIST_URL="http://mirrorlist.centos.org/?release=$SUITE&arch=$ARCH&repo=os"
    
    # download centos-release.rpm
	DOWNLOAD_OK=no
    for trynumber in 1 2 3; do
        [ $trynumber != 1 ] && echo "Trying again..."
        MIRROR_URL=$($WGET -qO- $MIRRORLIST_URL | head -n1)
        # MIRROR_URL=$(curl -s -S -f "$MIRRORLIST_URL" | head -n1 | tail -n1)
        if [ $? -ne 0 ] || [ -z "$MIRROR_URL" ]; then
            echo "Failed to get a mirror"
            continue
        fi
        RELEASE_URL="${MIRROR_URL}Packages/centos-release-$RELEASE.$ARCH.rpm"
        
        message "Fetching from: $RELEASE_URL"
        wget --directory-prefix="$INSTALL_ROOT" $RELEASE_URL
        # curl -f "$RELEASE_URL" > $INSTALL_ROOT/centos-release-$RELEASE.$ARCH.rpm
        if [ $? -ne 0 ]; then
            echo "Failed to download CentOS release rpm"
            continue
        fi
        DOWNLOAD_OK=yes
        RELEASE_FILE=$(basename $RELEASE_URL)
        break
    done
    
    if [ $DOWNLOAD_OK != yes ]; then
        return 1
    fi

	# make yum cache
    $YUM makecache
	info "Yum cache metadata created"
		
	# install centos-release
    $RPM --nodeps -ivh "${INSTALL_ROOT}/${RELEASE_FILE}"
    
    debug " - installing yum and rpm"
	$YUM install rpm-build yum   
    if [ $? -ne 0 ]; then
	# download and install base system
	PKG_BASE="bash-4|basesystem-|^filesystem-|^setup-|rootfiles-|MAKEDEV-|initscripts-|ca-certificates-|tzdata-|hwdata-|^yum-3|^yum-plugin-fastestmirror-|^python-urlgrabber-|^python-iniparse-"
	debug "Download noarch and core archives"
	PKG_MIRROR=`wget -q --force-html --no-parent -O - ${MIRROR_URL}Packages/ | sed -n "/href/ s/.*href=['\"]\([^'\"]*\)['\"].*/\1/gp" | egrep -i ".rpm$" | egrep -i $PKG_BASE`
	# PACKAGES=$(echo $PKG_MIRROR | egrep -i "$PKG_BASE")
	for pkg in $PKG_MIRROR; do
		PACKAGE=${MIRROR_URL}Packages/$pkg
		debug " - downloading $pkg"
		# wget -r -l1 --no-parent -A "$PKG_BASE" --directory-prefix="$YUM_CACHE" "${MIRROR_URL}Packages/"
		wget -q -N --directory-prefix="$YUM_CACHE" -e robots=off --wait 1 $PACKAGE
	done
	# install all downloaded packages
	$RPM -ivh --nodeps $YUM_CACHE/*.rpm
	fi
	
    # Mount /dev (required for yum)
    mkdir $INSTALL_ROOT/dev/ -p
    mount -o bind /dev $INSTALL_ROOT/dev/	
    
	# rebuild db
	chroot $INSTALL_ROOT rpm --rebuilddb
    
    # create a dummy resolvconf
    cp /etc/resolv.conf $INSTALL_ROOT/etc/resolv.conf
    
	PKG_LIST="python rpm sudo rpm-python dhclient openssh-server passwd rsyslog vim-minimal vixie-cron wget which libxml2 gnupg2 glib2 gpgme libxml2-python pygpgme python-pycurl PyXML rsyslog  chkconfig policycoreutils openssh-clients openssl curl"
	
    # instalar desde dentro de la chroot, garantiza su instalacion
    cp $INSTALL_ROOT/var/cache/yum/base/packages/* $INSTALL_ROOT/var/cache/yum/$ARCH/$SUITE/base/packages/
    debug "- Install all packages in chroot environment"
    chroot $INSTALL_ROOT rpm -ivh /centos-release-*.rpm
    # chroot $INSTALL_ROOT yum -y --nogpgcheck --disablerepo=updates update yum rpm python
    chroot $INSTALL_ROOT yum -y --nogpgcheck --disablerepo=updates install rpm-python rpm yum $PKG_LIST
    if [ $? -ne 0 ]; then
		umount -f $INSTALL_ROOT/dev/
		echo "Failed to download the rootfs, aborting."
		return 1
    fi
    
    # clean cache
    chroot $ROOTFS yum clean all
    # chroot $INSTALL_ROOT rm -f /var/lib/rpm/__*
    
    # umount dev
    umount -f $INSTALL_ROOT/dev/

	mv "$INSTALL_ROOT" "$CACHE/$DIST/$SUITE/rootfs-$ARCH"
    info "Download $DIST $SUITE complete."
 
    return 0    
}

# make a local copy of the mini centos
copy_centos()
{
    info "Copying rootfs to $ROOTFS..."
    rsync -aqzpHSW $CACHE/$DIST/$SUITE/rootfs-$ARCH/* $ROOTFS/ || return 1
    if [ $? -ne 0 ]; then
		error "Failed to copy rootfs"
        exit 1
    fi
    return 0
}

# install centos cache in rootfs
install_centos()
{
    mkdir -p /var/lock/subsys/
    (
        flock -n -x 200
        if [ $? -ne 0 ]; then
            error "Cache repository is busy."
            exit 1
        fi
        
        # cleaning cache of mini centos
        if [ "$CLEAN_CACHE" -eq "1" ]; then
			message "Cache found in $CACHE/$DIST/$SUITE/rootfs-$ARCH. clearing ..."
			rm --preserve-root --one-file-system -fR $CACHE/$DIST/$SUITE/rootfs-$ARCH && echo "Done." || exit 1
        fi
        
        # check the mini debian was not already downloaded
        message "Checking cache download in $CACHE/$DIST/$SUITE/rootfs-$ARCH ... "
        if [ ! -e "$CACHE/$DIST/$SUITE/rootfs-$ARCH" ]; then
            download_centos
            if [ $? -ne 0 ]; then
                error "Failed to download 'CentOS Base'"
                exit 1
            fi
        fi

        copy_centos
        
        return 0

        ) 200>/var/lock/subsys/lxc-centos

    return $?
}

centos_network()
{
	if [ "$DHCP" = "y" ]; then
		# configure using DHCP
cat <<EOF > $ROOTFS/etc/sysconfig/network-scripts/ifcfg-$LAN_INTERFACE
DEVICE=$LAN_INTERFACE
BOOTPROTO=dhcp
ONBOOT=yes
NM_CONTROLLED=no
USERCTL=yes
PEERDNS=yes
IPV6INIT=no
TYPE=Ethernet
MTU=$MTU
EOF
cat <<EOF >> $ROOTFS/etc/hosts
# $HOSTNAME
127.0.1.1	$HOSTNAME $NAME
EOF
	else
cat <<EOF > $ROOTFS/etc/sysconfig/network-scripts/ifcfg-$LAN_INTERFACE
DEVICE=$LAN_INTERFACE
NETWORK=$NETWORK
NETMASK=$NETMASK
IPADDR=$IP
GATEWAY=$GATEWAY
BOOTPROTO=none
ONBOOT=yes
NM_CONTROLLED=no
USERCTL=yes
PEERDNS=yes
IPV6INIT=no
TYPE=Ethernet
MTU=$MTU
EOF
cat <<EOF >> $ROOTFS/etc/hosts
# $HOSTNAME
$IP	$HOSTNAME $NAME
EOF
	fi
# set the hostname
cat <<EOF > $ROOTFS/etc/sysconfig/network
NETWORKING=yes
NETWORKING_IPV6=no
HOSTNAME=$HOSTNAME
EOF
echo $NAME > $ROOTFS/etc/hostname
echo $HOSTNAME > $ROOTFS/etc/mailname
}

centos_devices()
{
	DEV="$ROOTFS/dev"
	mknod -m 666 $DEV/tty c 5 0
    for tty in $(seq 1 4); do
	if [ ! -e $DEV/tty$tty ]; then
	    mknod -m 666 $ROOTFS/dev/tty$tty c 4 $tty
	fi
    done	
    mknod -m 666 $DEV/zero c 1 5
    mknod -m 666 $DEV/random c 1 8
    mknod -m 666 $DEV/urandom c 1 9
    rm -f ${DEV}/pts
    mkdir -m 755 $DEV/pts
    rm -f ${DEV}/shm
    mkdir -m 1777 $DEV/shm
    mknod -m 600 $DEV/console c 5 1
    mknod -m 666 $DEV/full c 1 7
    mknod -m 600 $DEV/initctl p
    # Mount pseudo-filesystems
    mount -o bind /dev/pts "$ROOTFS/dev/pts"
    mount -o bind /proc "$ROOTFS/proc"
    mount -o bind /sys "$ROOTFS/sys"
}

centos_inittab() {
cat <<EOF > $ROOTFS/etc/inittab
id:3:initdefault:
si::sysinit:/etc/init.d/rcS
l0:0:wait:/etc/init.d/rc 0
l1:1:wait:/etc/init.d/rc 1
l2:2:wait:/etc/init.d/rc 2
l3:3:wait:/etc/init.d/rc 3
l4:4:wait:/etc/init.d/rc 4
l5:5:wait:/etc/init.d/rc 5
l6:6:wait:/etc/init.d/rc 6
# Normally not reached, but fallthrough in case of emergency.
z6:6:respawn:/sbin/sulogin
1:2345:respawn:/sbin/getty 38400 console
c1:12345:respawn:/sbin/getty 38400 tty1 linux
c2:12345:respawn:/sbin/getty 38400 tty2 linux
c3:12345:respawn:/sbin/getty 38400 tty3 linux
c4:12345:respawn:/sbin/getty 38400 tty4 linux
EOF
}

configure_centos()
{
	# configure via mknod devices
	centos_devices
	# configure debian network
	centos_network
	# inittab
	centos_inittab
	# running basic centos hooks
	CENTOS="$TEMPLATEDIR/centos.d"
	for f in $(find $CENTOS/* -maxdepth 1 -type f | sort --numeric-sort); do
		. $f
	done
}

centos_cleanup()
{
	#
	# yum clean cache
	#
	chroot $ROOTFS /usr/bin/yum clean all
    # Unmount pseudo-filesystems
    umount -f $ROOTFS/dev/pts
    umount -f $ROOTFS/proc
    umount -f $ROOTFS/sys	
}

create_container()
{
	info "= Creating a CentOS-Based LXC container ="
	# create cache and install centos
	install_centos
    if [ $? -ne 0 ]; then
       error "Failed to install a 'CentOS Base' container"
       exit 1
    fi	
	# configure chroot
	configure_centos
    if [ $? -ne 0 ]; then
       error "Failed to configure centos container"
       exit 1
    fi
}


cleanup_container()
{
	# cleanup centos
	centos_cleanup
	info "CentOS LXC Container created"
	return 0
}
