#!/bin/bash
##
#  /usr/lib/lxc-tools/templates.d/lxc-canaima
#
#  Build a canaima container from debian rules
##
#
# debootstrap debian install
#
# based on:
# Daniel Lezcano <daniel.lezcano@free.fr>
# Authors:
# Jesus Lara <jesuslarag@phenobarbital.info>
# Luis Alejandro Martínez Faneyth <martinez.faneyth@gmail.com>
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA

DIST='Canaima'
SUITE='kerepakupai'
CANAIMA_PACKAGES='canaima-llaves lsb-base base-files'
MIRROR='http://paquetes.canaima.softwarelibre.gob.ve/'

download_canaima() 
{
	if [ "$ARCH" = 'x86_64' ]; then
		arch='amd64'
	else
		arch='i386'
	fi
	
    mkdir -p "$CACHE/$DIST/$SUITE/partial-$arch"
    if [ $? -ne 0 ]; then
       	error "Failed to create '$CACHE/$DIST/$SUITE/partial-$arch' directory"
       	return 1
    fi
    # download a mini debian into a cache
    message "Downloading Canaima Base ..."
    debootstrap --verbose --variant=$VARIANT --arch=$arch --include $CANAIMA_PACKAGES $EXTRA_PACKAGES \
        $SUITE $CACHE/$DIST/$SUITE/partial-$arch $MIRROR
    RESULT=$?

    if [ "$RESULT" != "0" ]; then
       error "Failed to download the rootfs, aborting."
       rm -fR "$CACHE/$DIST/$SUITE/partial-$arch"
       return 1
    fi

    mv "$CACHE/$DIST/$SUITE/partial-$arch" "$CACHE/$DIST/$SUITE/rootfs-$arch"
    info "Download $DIST $SUITE complete."

    return 1
}

copy_canaima()
{
	# make a local copy of the minidebian
	if [ "$ARCH" = 'x86_64' ]; then
		arch='amd64'
	else
		arch='i386'
	fi	
    info "Copying $DIST rootfs to $ROOTFS..."
    rsync -aqzpHSW $CACHE/$DIST/$SUITE/rootfs-$arch/* $ROOTFS/ || return 1
    if [ $? -ne 0 ]; then
		error "Failed to copy $DIST rootfs"
        return 1
    fi
}

install_canaima() 
{

    mkdir -p /var/lock/subsys/
    (
        flock -n -x 200
        if [ $? -ne 0 ]; then
            error "Cache repository is busy."
            return 1
        fi
        
		if [ "$ARCH" = 'x86_64' ]; then
			arch='amd64'
		else
			arch='i386'
		fi	        
		
        # cleaning cache of mini debian
        if [ "$CLEAN_CACHE" -eq "1" ]; then
			message "Cache found in $CACHE/$DIST/$SUITE/rootfs-$arch. clearing ..."
			rm -fR $CACHE/$DIST/$SUITE/rootfs-$arch
        fi
        
        # check canaima-base cache was not already downloaded
        message "Checking cache download in $CACHE/$DIST/$SUITE/rootfs-$arch ... "
        if [ ! -e "$CACHE/$DIST/$SUITE/rootfs-$arch" ]; then
            download_canaima
            if [ $? -ne 0 ]; then
                error "Failed to download 'Canaima Base'"
                return 1
            fi
        fi
        
        copy_canaima
        
        return 0

        ) 200>/var/lock/subsys/lxc

    return $?
}

canaima_network()
{
	if [ "$DHCP" = "y" ]; then
cat <<EOF >> $ROOTFS/etc/network/interfaces
# interface $LAN_INTERFACE
auto $LAN_INTERFACE
iface $LAN_INTERFACE inet dhcp
EOF
cat <<EOF >> $ROOTFS/etc/hosts
# $HOSTNAME
127.0.1.1	$HOSTNAME $NAME
EOF
	else
cat <<EOF >> $ROOTFS/etc/network/interfaces
# interface $LAN_INTERFACE
auto $LAN_INTERFACE
iface $LAN_INTERFACE inet static
	address $IP
	netmask $NETMASK
	network $NETWORK
	gateway $GATEWAY
EOF
cat <<EOF >> $ROOTFS/etc/hosts
# $HOSTNAME
$IP	$HOSTNAME $NAME
EOF
	fi
# set the hostname
echo $NAME > $ROOTFS/etc/hostname
echo $HOSTNAME > $ROOTFS/etc/mailname

}

configure_canaima()
{
	# configure inittab
	canaima_inittab
	# configure via mknod devices
	canaima_devices
	# configure debian network
	canaima_network
    if [ $? -ne 0 ]; then
		error "Failed to Configure 'Canaima Base'"
		return 1
    fi		
	# running basic debian hooks
	CANAIMA="$TEMPLATEDIR/canaima.d"
	for f in $(find $CANAIMA/* -maxdepth 1 -type f | sort --numeric-sort); do
		. $f
	done
}

canaima_devices()
{
	DEV="$ROOTFS/dev"
	mknod -m 666 ${DEV}/tty c 5 0
    for tty in $(seq 1 2); do
	if [ ! -e $DEV/tty$tty ]; then
	    mknod -m 666 $ROOTFS/dev/tty$tty c 4 $tty
	fi
    done
    rm -f ${DEV}/null
	mknod -m 666 ${DEV}/null c 1 3
	rm -f ${DEV}/zero
    mknod -m 666 ${DEV}/zero c 1 5
    rm -f ${DEV}/random
    mknod -m 666 ${DEV}/random c 1 8
    rm -f ${DEV}/urandom
    mknod -m 666 ${DEV}/urandom c 1 9
    rm -f ${DEV}/console
    mknod -m 600 ${DEV}/console c 5 1
    rm -f ${DEV}/full
    mknod -m 666 ${DEV}/full c 1 7
    # Mount pseudo-filesystems
    mount -o bind /dev/pts "$ROOTFS/dev/pts"
    mount -o bind /proc "$ROOTFS/proc"
    mount -o bind /sys "$ROOTFS/sys"
	# Bind mount systems apt cache
    mount -o bind /var/cache/apt/archives "$ROOTFS/var/cache/apt/archives"
    # configure a minimal fstab for container
cat <<EOF > $ROOTFS/etc/fstab
/dev/root               /                       rootfs   defaults        0 0
devpts                  /dev/pts                devpts  gid=5,mode=620,newinstance,ptmxmode=0666  0 0
none                    /dev/shm                tmpfs    nosuid,nodev    0 0
EOF
}

canaima_inittab() {
	
cat <<EOF > $ROOTFS/etc/inittab
id:3:initdefault:
si::sysinit:/etc/init.d/rcS
l0:0:wait:/etc/init.d/rc 0
l1:1:wait:/etc/init.d/rc 1
l2:2:wait:/etc/init.d/rc 2
l3:3:wait:/etc/init.d/rc 3
l4:4:wait:/etc/init.d/rc 4
l5:5:wait:/etc/init.d/rc 5
l6:6:wait:/etc/init.d/rc 6
# Normally not reached, but fallthrough in case of emergency.
z6:6:respawn:/sbin/sulogin
1:2345:respawn:/sbin/getty 38400 console
c1:12345:respawn:/sbin/getty 38400 tty1 linux
c2:12345:respawn:/sbin/getty 38400 tty2 linux
#c3:12345:respawn:/sbin/getty 38400 tty3 linux
#c4:12345:respawn:/sbin/getty 38400 tty4 linux
EOF

}

cleanup_canaima()
{
	#
	# clean apt cache
	#
	chroot $ROOTFS /usr/bin/apt-get -y autoremove
	chroot $ROOTFS /usr/bin/apt-get -y clean
	# protect dash and locales
	chroot $ROOTFS /bin/echo locales hold | /usr/bin/dpkg --set-selections
	chroot $ROOTFS /bin/echo dash hold | /usr/bin/dpkg --set-selections
	#  Remove disable-daemons script (if present)
	if [ -x "$ROOTFS/usr/sbin/policy-rc.d" ]; then
		rm -f "$ROOTFS/usr/sbin/policy-rc.d"
	fi
	# Unmount systems apt cache
    umount "$ROOTFS/var/cache/apt/archives"
    rm -f "$ROOTFS/etc/dpkg/dpkg.cfg.d/lxc"
    # Unmount pseudo-filesystems
    umount "$ROOTFS/dev/pts"
    umount "$ROOTFS/proc"
    umount "$ROOTFS/sys"
}


create_container()
{
	info "= Creating a Canaima-Base LXC container ="
	# create cache and install Debian
	install_canaima
    if [ $? -ne 0 ]; then
		error "Failed to download 'Canaima Base'"
		return 1
    fi	
	debug "= Configure Canaima-Based LXC container ="
	# configure chroot
	configure_canaima
    if [ $? -ne 0 ]; then
		error "Failed to configure 'Canaima Base'"
		return 1
    fi	
	info "Canaima Base LXC Container created"
	return 0
}

cleanup_container()
{
	# cleanup debian
	cleanup_canaima
	return 0
}
